language: cpp
compiler: gcc

dist: xenial
sudo: required

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev

script:
  - cmake .
  - cmake --build . --target MinionCrusher -- -j 4