language: cpp
compiler: gcc

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev

script:
  - cmake .
  - cmake --build .